# Generated by Django 4.1.7 on 2023-05-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Declined', 'Decline')], default='Pending', max_length=50),
        ),
    ]
